// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJgQ9uSkzo5o4XXgdPVnNp3EZSa7WLM1U',
    appId: '1:371080348175:web:467fc697b8055f63a7997a',
    messagingSenderId: '371080348175',
    projectId: 'iic-flutter-application',
    authDomain: 'iic-flutter-application.firebaseapp.com',
    storageBucket: 'iic-flutter-application.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvMDbUeDhxn3oNZYzScvW3fPBLUiB6NLE',
    appId: '1:371080348175:android:996717486a4d9248a7997a',
    messagingSenderId: '371080348175',
    projectId: 'iic-flutter-application',
    storageBucket: 'iic-flutter-application.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOxYy1PQjhK5Gw61RyLjM7sENA0NcJBeM',
    appId: '1:371080348175:ios:a7d38f35675bebb0a7997a',
    messagingSenderId: '371080348175',
    projectId: 'iic-flutter-application',
    storageBucket: 'iic-flutter-application.appspot.com',
    iosClientId:
        '371080348175-a2jcvop284qhkcik1m83llfba430cr15.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOxYy1PQjhK5Gw61RyLjM7sENA0NcJBeM',
    appId: '1:371080348175:ios:a7d38f35675bebb0a7997a',
    messagingSenderId: '371080348175',
    projectId: 'iic-flutter-application',
    storageBucket: 'iic-flutter-application.appspot.com',
    iosClientId:
        '371080348175-a2jcvop284qhkcik1m83llfba430cr15.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginApp',
  );
}
